site_name: CLI Order Executor (v1.19.3)
theme:
  name: swan
extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - Risk Management: risk-management.md
  - Commands:
    - Open Order by Risk: open-order-by-risk.md
    - Open Order by Quantity: open-order-by-quantity.md
    - Close Position: close-position.md
    - Cancel Limit Orders: cancel-limit-orders.md
    - Cancel Conditional Orders: cancel-conditional-orders.md
    - Manage Stop-Loss: manage-stop-loss.md
    - Manage Take-Profit: manage-take-profit.md
    - Set Leverage: set-leverage.md
    - Get Position Info: get-position-info.md
    - Get Limit Orders: get-limit-orders.md
    - Get Conditional Orders: get-conditional-orders.md
    - Get Wallet Balance: get-wallet-balance.md
    - Send Test API Request: send-test-api-request.md
    - Get Documentation Link: get-documentation-link.md
    - Exit Program: exit-program.md
  - How to Use?: how-to-use.md
  - Error 10002: error-10002.md
